
#include "cuda_runtime.h"
#include "device_launch_parameters.h"

#include <stdio.h>

cudaError_t addWithCuda(int *c, const int *a, const int *b);

__global__ void addKernel(int *c, const int *a, const int *b)
{
    int i = blockIdx.x * 12 + blockIdx.y*4 + threadIdx.x*2 + threadIdx.y;
    c[i] = a[i] + b[i];
}

int main()
{
    /*const int arraySize = 6;
    const int a[arraySize] = { 1, 2, 3, 4, 5, 6 };
    const int b[arraySize] = { 10, 20, 30, 40, 50, 60 };
    int c[arraySize] = { 0 };*/


    /*const int arraySize = 3;
    const int a[arraySize][arraySize] = { {1,2,3},{4,5,6},{7,8,9} };
    const int b[arraySize][arraySize] = { {10,20,30},{40,50,60},{70,80,90} };
    int c[arraySize][arraySize] = { {0,0,0} };*/


    // GEMINI USED TO GENERATE ARRAYS BECAUSE I DONT HATEMYSELF
    int a[2][3][2][2] = {
        { // Outer Row 0
            {{1, 2}, {3, 4}}, // 2x2 Grid at [0][0]
            {{5, 6}, {7, 8}}, // 2x2 Grid at [0][1]
            {{9, 0}, {1, 2}}  // 2x2 Grid at [0][2]
        },
        { // Outer Row 1
            {{3, 4}, {5,6}}, // 2x2 Grid at [1][0]
            {{7, 8}, {9, 0}}, // 2x2 Grid at [1][1]
            {{1, 2}, {3, 4}}  // 2x2 Grid at [1][2]
        }
    };




    int b[2][3][2][2] = {
    { // Outer Row 0
        {{10, 20}, {30, 40}}, // [0][0]
        {{50, 60}, {70, 80}}, // [0][1]
        {{90,  0}, {10, 20}}  // [0][2]
    },
    { // Outer Row 1
        {{30, 40}, {50, 60}}, // [1][0]
        {{70, 80}, {90,  0}}, // [1][1]
        {{10, 20}, {30, 40}}  // [1][2]
    }
    };

    int c[2][3][2][2] = {};

    // Add vectors in parallel.
    cudaError_t cudaStatus = addWithCuda(&c[0][0][0][0], &a[0][0][0][0], &b[0][0][0][0]);
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "addWithCuda failed!");
        return 1;
    }

    // PRINTF GENERATED BY GEMINI BECASE I DONT HATE YMSELF
    printf(
        "--- ROW 0 ---\n"
        "[%2d %2d]  [%2d %2d]  [%2d %2d]\n"
        "[%2d %2d]  [%2d %2d]  [%2d %2d]\n\n"
        "--- ROW 1 ---\n"
        "[%2d %2d]  [%2d %2d]  [%2d %2d]\n"
        "[%2d %2d]  [%2d %2d]  [%2d %2d]\n",
        // Row 0, Box 0       Row 0, Box 1       Row 0, Box 2
        c[0][0][0][0], c[0][0][0][1], c[0][1][0][0], c[0][1][0][1], c[0][2][0][0], c[0][2][0][1],
        c[0][0][1][0], c[0][0][1][1], c[0][1][1][0], c[0][1][1][1], c[0][2][1][0], c[0][2][1][1],

        // Row 1, Box 0       Row 1, Box 1       Row 1, Box 2
        c[1][0][0][0], c[1][0][0][1], c[1][1][0][0], c[1][1][0][1], c[1][2][0][0], c[1][2][0][1],
        c[1][0][1][0], c[1][0][1][1], c[1][1][1][0], c[1][1][1][1], c[1][2][1][0], c[1][2][1][1]
    );

    // cudaDeviceReset must be called before exiting in order for profiling and
    // tracing tools such as Nsight and Visual Profiler to show complete traces.
    cudaStatus = cudaDeviceReset();
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaDeviceReset failed!");
        return 1;
    }

    return 0;
}

// Helper function for using CUDA to add vectors in parallel.
cudaError_t addWithCuda(int *c, const int *a, const int *b)
{

    int *dev_a;
    int *dev_b;
    int *dev_c;
    cudaError_t cudaStatus;

    // Choose which GPU to run on, change this on a multi-GPU system.
    cudaStatus = cudaSetDevice(0);
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaSetDevice failed!  Do you have a CUDA-capable GPU installed?");
        goto Error;
    }

    // Allocate GPU buffers for three vectors (two input, one output)    .
    cudaStatus = cudaMalloc((void**)&dev_c, 2 * 2 * 2 * 3 * sizeof(int));
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaMalloc failed!");
        goto Error;
    }

    cudaStatus = cudaMalloc((void**)&dev_a, 2 * 2 * 2 * 3 * sizeof(int));
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaMalloc failed!");
        goto Error;
    }

    cudaStatus = cudaMalloc((void**)&dev_b, 2 * 2 * 2 * 3 * sizeof(int));
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaMalloc failed!");
        goto Error;
    }

    // Copy input vectors from host memory to GPU buffers.
    cudaStatus = cudaMemcpy(dev_a, a, 2 * 2 * 2 * 3 * sizeof(int), cudaMemcpyHostToDevice);
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "A cudaMemcpy failed!");
        goto Error;
    }

    cudaStatus = cudaMemcpy(dev_b, b, 2 * 2 * 2 * 3 * sizeof(int), cudaMemcpyHostToDevice);
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "B cudaMemcpy failed!");
        goto Error;
    }

    // Launch a kernel on the GPU with one thread for each element.
    addKernel<<<dim3(2,3), dim3(2, 2)>>>(dev_c, dev_a, dev_b);

    // Check for any errors launching the kernel
    cudaStatus = cudaGetLastError();
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "addKernel launch failed: %s\n", cudaGetErrorString(cudaStatus));
        goto Error;
    }
    
    // cudaDeviceSynchronize waits for the kernel to finish, and returns
    // any errors encountered during the launch.
    cudaStatus = cudaDeviceSynchronize();
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaDeviceSynchronize returned error code %d after launching addKernel!\n", cudaStatus);
        goto Error;
    }

    // Copy output vector from GPU buffer to host memory.
    cudaStatus = cudaMemcpy(c, dev_c, 2 * 2 * 2 * 3 * sizeof(int), cudaMemcpyDeviceToHost);
    if (cudaStatus != cudaSuccess) {
        fprintf(stderr, "cudaMemcpy failed!");
        goto Error;
    }

Error:
    cudaFree(dev_c);
    cudaFree(dev_a);
    cudaFree(dev_b);
    
    return cudaStatus;
}
